{% set version = "1.20.0" %}

package:
  name: ucx-split
  version: {{ version }}

source:
  url: https://github.com/openucx/ucx/releases/download/v{{ version }}/ucx-{{ version }}.tar.gz
  sha256: 8a2776c3e8d7da8aa45abe640a6956b33f71b59cf4120566a888ee2b0ecfe667

build:
  skip: true  # [(not linux) or cuda_compiler_version in (undefined, "None", "12.6")]
  number: 2

outputs:
  - name: ucx
    version: {{ version }}
    build:
      run_exports:
        - {{ pin_subpackage("ucx", max_pin="x.x") }}
      ignore_run_exports_from:
        - {{ compiler("cuda") }}
        - cuda-cudart-dev         # [cuda_compiler == "cuda-nvcc"]
      missing_dso_whitelist:
        - "*libcuda.so*"
        - "*libcudart.so*"
        - "*libnvidia-ml.so*"
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - automake
        - autoconf
        - libtool
        - make
        - pkg-config
        - libgomp
      host:
        - cuda-version {{ cuda_compiler_version }}
        - cuda-cudart-dev                                           # [cuda_compiler == "cuda-nvcc"]
        - cuda-nvml-dev                                             # [cuda_compiler == "cuda-nvcc"]
        - rdma-core
      run_constrained:
        - {{ pin_compatible("cuda-version", min_pin="x") }}         # [cuda_compiler == "cuda-nvcc"]
        # The actual version constraint comes from cuda-version, so below we explicit list
        # them only to codify that these are expected (but optional) dependencies when CUDA
        # is in use.
        - cuda-cudart                                               # [cuda_compiler == "cuda-nvcc"]

    script: install_ucx.sh
    test:
      commands:
        - test -f "${PREFIX}/lib/libucp${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucp.a"
        - test -f "${PREFIX}/lib/libucm${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucm.a"
        - test -f "${PREFIX}/lib/libucs${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libucs.a"
        - test -f "${PREFIX}/lib/libuct${SHLIB_EXT}"
        - test ! -f "${PREFIX}/lib/libuct.a"
        - test -f "${PREFIX}/bin/.ucx-post-link.sh"
        - test -f "${PREFIX}/bin/ucx_info"
        # Fails on ppc64le
        - ucx_info -v  # [not ppc64le]
    about:
      home: https://openucx.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: Unified Communication X.
      dev_url: https://github.com/openucx/ucx
      doc_url: https://openucx.readthedocs.io/

about:
  home: https://github.com/openucx/ucx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Unified Communication X.
  dev_url: https://github.com/openucx/ucx
  doc_url: https://openucx.readthedocs.io/

extra:
  recipe-maintainers:
    - bdice
    - marcinz
    - Akshay-Venkatesh
    - jakirkham
    - quasiben
    - TomAugspurger
    - leofang
    - matthiasdiener
    - xhochy
    - pentschev
